Data-Liberation-Front/csvlint.rb

- lib/csvlint/validate.rb
From #105 
>Several date and time formats were blindly imported from Rails' Date/Time formats, but I'd expect several of those are never in a CSV (e.g. the 23 digit timestamp with nanoseconds).
I've removed the long numbers-only date/time formats, because these can false positive, e.g. if you have 6-digit identifiers, a lot of them will look like dates, e.g. 12340101.
There are very likely other formats that can be removed due to their never appearing in CSVs.
Fixes #106
> eliminate some date and time formats, related #105

- .travis.yml
- features/fixtures/inconsistent-line-endings-unquoted.csv
- features/validation_errors.feature
- lib/csvlint/validate.rb
(The test didn't fail on Travis, but it certainly failed locally until the next commit was made.)
> Match another CSV error about line endings

- features/step_definitions/information_steps.rb
- features/step_definitions/validation_errors_steps.rb
- features/step_definitions/validation_info_steps.rb
- features/step_definitions/validation_warnings_steps.rb
Ruby builds always seem pretty chatty. The warnings about .should are pretty benign, but this patch silences it so quites the build down a touch.
> Fixed warning - use expect( ) rather than .should

- lib/csvlint/field.rb
- spec/field_spec.rb
Have been looking at https://github.com/theodi/csvlint/issues/180, and have managed to chase it down.
While Ruby's URI library treats almost anything as a URI, it will still choke if there are invalid characters. This PR catches these errors and returns an `ArgumentError` instead, which the `Field.validate_column` will catch and return a value of `false`, rather than crapping out unhelpfully
> Catch invalid URIs

- README.md
- bin/csvlint
- lib/csvlint/schema.rb
- spec/schema_spec.rb
This feature fixes #126. Happy to make changes if requested. Ruby is not my first language.
> Emit a warning when the CSV header does not match the supplied schema

- lib/csvlint/schema.rb
This small change uses the CSV module rather than a naive join(',') to create the observed vs expected headers in the error message. This will result in better messages if headers include commas.
> Validate header size improvement

- features/schema_validation.feature
- lib/csvlint/error_collector.rb
- lib/csvlint/field.rb
- lib/csvlint/schema.rb
- lib/csvlint/validate.rb
Replacement of conditional statement to see if a regular expression was
created with a RegexpError rescue to catch when creation failed and act
accordingly.
> Invalid schema

- lib/csvlint/csvw/number_format.rb
- lib/csvlint/validate.rb
- spec/csvw/number_format_spec.rb
Validating CKAN URLs which had link-headers, but not link-headers pertaining to CSVW, caused errors, because it was trying to parse things that didn't exist
> Catch errors if link headers are don't have particular values

- lib/csvlint/validate.rb
This is a legacy from when `parse_line` was only used within `validate_url`. We now join the leading and the chunk within `parse_line`
> Don't pass leading string to parse_line

- lib/csvlint/validate.rb
Memoizes the result of CSV#encode_str, CSV#escape_re, and disables CSV's converters feature.
At this point, the two big bottlenecks are `build_formats` (already optimized, but eliminating some `if` branches will make it faster), and `CSV#init_separators`, which is slow because determining the `row_sep` is slow.
Call graph after memoizing `escape_re`:
After memoizing `encode_str`:
)
After disabling converters:
> More optimizations after #157

- lib/csvlint/validate.rb
Calling `CSV.new` twice for each line of a CSV is expensive, and the slowest part of that is calling `encode_re` on the same string thousands of times (this is the biggest bottleneck). This patch memoizes return values and produces the following graph:
> Memoize the result of CSV#encode_re

- features/csvupload.feature
- features/validation_info.feature
- lib/csvlint/validate.rb
This does three things:
* Stops calling a lambda if one isn't specified
* Checks to see if a string is a possible date before running all the date regexes in `build_formats ` (if it begins with a number or a month)
* Gets the linebreaks by checking the end of a string, rather than running `CSV.new` again
> Further optimisations

- lib/csvlint/validate.rb
I noticed that invalid characters were causing failures when parsing files. This works for both files and URLs now
> Check characters in validate_line method

- README.md
eg, JSON seems to require "http://www.w3.org/2001/XMLSchema#integer",
not just "integer"
> Update schema file example to clarify type

- lib/csvlint/validate.rb
This fixes a problem where the line number would not increment after an invalid_encoding error was thrown on a line. All the subsequent errors provided would then show the wrong line number.
> still increment current_line after invalid_encoding error

- lib/csvlint/csvw/table.rb
Improvements to output on foreign key error and duplicate key error:
* Sets "row" on foreign key error (it used to always be nil)
* Sets "col" on foreign key error and on duplicate key error, where the key has exactly one column.  Otherwise "col" remains nil.
> Add row + col to foreign key & duplicate key errors

- lib/csvlint/schema.rb
Trapping and binning this exception allowed me to actually use this
code in a real-world situation. Crucially (maybe), all the specs still
pass
> Trap-and-bin this

- lib/csvlint/validate.rb
ASCII-8BIT implies that it’s been read from the file system; in that
case, let’s assume UTF-8. I think this should really be picking up the
encoding from the dialect but I’m wary about fiddling around too much
> force UTF-8 if encoding is ASCII-8BIT

- lib/csvlint/cli.rb
I've added an option to the cli `--werror` to ensure that any warnings cause a failing exit - the same behaviour as errors.
There was also a bug with the --dump-errors option, the option was defined as :dump_errors, but was referenced in code as :dump. This has been resolved.
-          valid &= validate_csv(source, schema, options[:dump])
-          valid &= validate_csv(source, schema, options[:dump_errors])
RSpec tests and Cucumber features have been run with no failures.
> Changes to CLI - Added --werror option, fixed bug with --dump_errors option.

- lib/csvlint/validate.rb
- `csvlint` library patched the method `CSV#init_converters`
- https://github.com/theodi/csvlint.rb/blob/master/lib/csvlint/validate.rb#L43-L49
- It's not compatible with ruby `2.5.0`
- In earlier versions of ruby, it only accepts two arguments:
- https://docs.ruby-lang.org/en/2.4.0/CSV.html#method-i-init_converters
- However, in ruby `2.5.0`, the required arguments are increased to three
- https://docs.ruby-lang.org/en/2.5.0/CSV.html#method-i-init_converters
- By removing this patch, `LineCSV` will fallback and use the default `#init_converters` method of `CSV` for ruby `2.5.0` and above.
- Currently, when using `csvlint` on `ruby 2.5.0`, all validations are raising exceptions with `:invalid_encoding` message. When it's not really the cause of the issue.
- …
> Don't patch CSV#init_converters for ruby 2.5 compatibility

- README.md
- correct typos in README: s/standolone/standalone/g
> correct typos in README

- csvlint.gemspec
- lib/csvlint.rb
- Drop `mime-types` gem dependency
Because
- It's introduced at https://github.com/theodi/csvlint.rb/commit/cc41f9a9f0bdc56d722cabe0ed05df320b48ffbc
- But it's no longer used since https://github.com/theodi/csvlint.rb/commit/02ce93d11ca3a42d8d032f358ed8167eeb7dc710
> Drop mime-types gem dependency

- csvlint.gemspec
- I would like to remove specific version of net-http-persistent in gemspec if there is no special reason.
> remove specific version of net-http-persistent in gemspec

- csvlint.gemspec
- lib/csvlint/cli.rb
This PR fixes #214
- Remove 'colorize' and  use 'rainbow' as production dependencies
- Only enable 'rainbow' if `$stdout.tty?` to keep behavior the same as it was previously
The first commit uses `rainbow/refinements` to make the code as similar to the `colorize` version as possible, but that breaks Ruby-2.0.0 compatibility. Now uses Rainbow's "presenter" style to support all the versions currently configured in Travis.
Using Rainbow introduces a risk for future maintainers: Rainbow colorizes based on a [global setting](https://github.com/sickill/rainbow#configuration).  So if some additional output stream (e.g., a separate warnings output file) were added, *and* the color refinements were called on it, they would be enabled/disabled based on the …
> Replace colorize with rainbow to make licensing consistent.

- csvlint.gemspec
2.4 is the oldest version of Ruby in support, and there are build failures currently on 2.6, so restrict the support to those versions in between.
> Ruby 2.4 now required, 2.6 not yet supported

- lib/csvlint/cli.rb
- lib/csvlint/validate.rb
- spec/schema_spec.rb
Use Csvlint::Schema.load_from_uri instead, as directed by the warning.
Cloning the repo and running `rake spec` only to be presented with a screenful of deprecation warnings was, erm, unsettling. This is a tiny change to resolve those warnings, although I haven't actually removed the deprecated method.
> Fix load_from_json deprecation warnings.

- features/support/load_tests.rb
- features/support/webmock.rb
This PR fixes the CSV-on-the-web tests by fetching them direct from github. The w3 URLs used before redirect to github, but do not use HTTPS, so cause errors when following the redirects. When that's fixed, we can change back to the canonical w3 URLs.
> Fix csvw tests

- lib/csvlint.rb
This PR fixes #229 
As is mentioned in the comments of the addressed issue, ruby 2.6 doesn't implement the `present?` method on `Object`. If we include that behavior it should continue to work 😃
> Include active_support/object to ensure this works in ruby 2.6

- lib/csvlint/field.rb
This PR improves the performance of regular expression-based validation. The changes in this PR reduced the time to validate a 10,000 line CSV file with 25 regular expression validations per line from 10 seconds to 1 second.
The results of the profiler run are as follows.
Before the change, most of the time is spent validating with regular expressions.
[before](https://gist.github.com/youpy/b6f5ead29f2afac24f5985e997642ba0)
[after](https://gist.github.com/youpy/b3316b84aab9399688761c747e6b7fc2)
- reduce instantiation of extra regular expression objects
> optimize validation with regular expression

- .standard_todo.yml
- lib/csvlint/csvw/column.rb
- lib/csvlint/csvw/property_checker.rb
- lib/csvlint/field.rb
- lib/csvlint/schema.rb
- lib/csvlint/validate.rb
This PR fixes:
- #284 
- #280
- Update syntax in accordance with StandardRb
- [Remove redundant returns](https://github.com/Data-Liberation-Front/csvlint.rb/commit/a5f2ec5c58abccd027bb9996015f7fb4d679b8fb)
- [Remove unnecessary parentheses](https://github.com/Data-Liberation-Front/csvlint.rb/commit/c023be9a5f11ec167db8a82de043dbc970dcdb22)
- [Use double quotes](https://github.com/Data-Liberation-Front/csvlint.rb/commit/f4bf8a4633c5506262e12c0fe210d87e7bc484f6)
- [Invert condition to not mix logical operator in an unless](https://github.com/Data-Liberation-Front/csvlint.rb/commit/cb0451b4ff45b48ee22e25954b6f43bd1930124f)
- [Ignore UselessRescue because used for test purposes](https://github.com/Data-Liberation-Front/csvlint.rb/pull/285/commits/f5c5990e …
> Update syntax from StandardRb specification and specify ActiveSupport version
